# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0002_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
